-- 1. Update the admin's password to the MD5 hash of "oops!"

UPDATE "users" SET "password" = '982c0381c279d139fd221fce974916e7' WHERE "username" = 'admin';


-- 2. Delete the log generated by changing the admin's password
-- Removes the log entry corresponding to the real update to "oops!"

DELETE FROM "user_logs" WHERE "new_password" = '982c0381c279d139fd221fce974916e7';


-- 3. Plant false log data framing 'emily33'
-- Inserts a record into 'user_logs' showing admin changed their password to emily33's password
INSERT INTO "user_logs" ("type", "old_username", "new_username", "old_password", "new_password")
VALUES (
    'update',
    'admin',
    'admin',
    (SELECT "password" FROM "users" WHERE "username" = 'admin'),
    (SELECT "password" FROM "users" WHERE "username" = 'emily33')
);
